updated waiting for file

diff --git a/azurepipelines.yml b/azurepipelines.yml
--- a/azurepipelines.yml
+++ b/azurepipelines.yml
@@ -42,25 +42,32 @@ stages:
 
     - upload: manifests
       artifact: manifests
- 
+
     - script: |
-       echo "Container Registry: $(containerRegistry)"
-       echo "Image Repository: $(imageRepository)"
-       echo "Tag: $(tag)"
-       echo "Replacing placeholders in manifests..."
+       FILE_PATH=$(Pipeline.Workspace)/manifests/deployment-staging.yml
+       MAX_RETRIES=60
+       RETRY_INTERVAL=10  # seconds
+       RETRY_COUNT=0
+    
+       while [ ! -f "$FILE_PATH" ] && [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
+        echo "File $FILE_PATH not found. Waiting for $RETRY_INTERVAL seconds..."
+         sleep $RETRY_INTERVAL
+       RETRY_COUNT=$((RETRY_COUNT + 1))
+      done
+    
+      if [ -f "$FILE_PATH" ]; then
+       echo "File $FILE_PATH found. Proceeding with the script."
        sed "s|$(containerRegistry)|$containerRegistry|g; s|$(imageRepository)|$imageRepository|g; s|$(tag)|$tag|g" $(Pipeline.Workspace)/manifests/deployment-staging.yml > $(Pipeline.Workspace)/manifests/deployment-staging.yml
        sed "s|$(containerRegistry)|$containerRegistry|g; s|$(imageRepository)|$imageRepository|g; s|$(tag)|$tag|g" $(Pipeline.Workspace)/manifests/deployment.yml > $(Pipeline.Workspace)/manifests/deployment.yml
-      displayName: 'Replace placeholders in manifest files'
+      else
+       echo "File $FILE_PATH not found after $((RETRY_COUNT * RETRY_INTERVAL)) seconds. Exiting."
+       exit 1
+      fi
+      displayName: 'Wait for file and then run script'
       env:
-       containerRegistry: $(containerRegistry)
-       imageRepository: $(imageRepository)
-       tag: $(tag)
-
-   # - task: PublishBuildArtifacts@1
-   #   displayName: 'Publish Coverage Reports'
-    #  inputs:
-     #   PathtoPublish: '$(Build.SourcesDirectory)/coverage'
-    #    ArtifactName: 'coverage-reports'
+        containerRegistry: $(containerRegistry)
+        imageRepository: $(imageRepository)
+        tag: $(tag)
 
 - stage: Deploy_Dev
   displayName: Deploy to Dev
