update

diff --git a/azurepipelines.yml b/azurepipelines.yml
--- a/azurepipelines.yml
+++ b/azurepipelines.yml
@@ -55,14 +55,14 @@ stages:
        RETRY_COUNT=$((RETRY_COUNT + 1))
       done
     
-      if [ -f "$FILE_PATH" ]; then
-       echo "File $FILE_PATH found. Proceeding with the script."
-       sed "s|$(containerRegistry)|$containerRegistry|g; s|$(imageRepository)|$imageRepository|g; s|$(tag)|$tag|g" $(Pipeline.Workspace)/manifests/deployment-staging.yml > $(Pipeline.Workspace)/manifests/deployment-staging.yml
-       sed "s|$(containerRegistry)|$containerRegistry|g; s|$(imageRepository)|$imageRepository|g; s|$(tag)|$tag|g" $(Pipeline.Workspace)/manifests/deployment.yml > $(Pipeline.Workspace)/manifests/deployment.yml
-      else
-       echo "File $FILE_PATH not found after $((RETRY_COUNT * RETRY_INTERVAL)) seconds. Exiting."
-       exit 1
-      fi
+       if [ -f "$FILE_PATH" ]; then
+        echo "File $FILE_PATH found. Proceeding with the script."
+        sed "s|$(containerRegistry)|$containerRegistry|g; s|$(imageRepository)|$imageRepository|g; s|$(tag)|$tag|g" $(Pipeline.Workspace)/manifests/deployment-staging.yml > $(Pipeline.Workspace)/manifests/deployment-staging.yml
+        sed "s|$(containerRegistry)|$containerRegistry|g; s|$(imageRepository)|$imageRepository|g; s|$(tag)|$tag|g" $(Pipeline.Workspace)/manifests/deployment.yml > $(Pipeline.Workspace)/manifests/deployment.yml
+       else
+        echo "File $FILE_PATH not found after $((RETRY_COUNT * RETRY_INTERVAL)) seconds. Exiting."
+        exit 1
+       fi
       displayName: 'Wait for file and then run script'
       env:
         containerRegistry: $(containerRegistry)
